ARG ORG=dockcross
FROM ${ORG}/base:latest

LABEL maintainer="Matt McCormick matt.mccormick@kitware.com"

ENV WINEARCH win64
ARG MXE_TARGET_ARCH=x86_64
ARG MXE_TARGET_THREAD=.posix
ARG MXE_TARGET_LINK=shared

#include "common.windows"

RUN \
  apt-get update && \
  apt-get install --no-install-recommends --yes \
  mingw-w64-tools \
  binutils-mingw-w64-x86-64

#include "common.label-and-env"
